<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Music Player </title>
    <script src="https://kit.fontawesome.com/93e3069a39.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/kodego.css">
</head>
<body>
    
<div class="middle">
    <div class="image">
        <!-- <img src="assets/red-al.jpg" alt=""> -->
        <img src="https://i.postimg.cc/HkwWnvMB/red-al.jpg" alt="taylor">
    </div>

    <div class="art">
        <h1>Red</h1>
        <p>Taylor Swift</p>
    </div>

    <div class="slider">
        <span class="current">5:53</span>
        <span class="duration">10:13</span>
        <input type="range" value="553" max="1013" min="0" class="bar">
    </div>

    <div class="control">
        <i class="fa-solid fa-backward-step"></i>
        <div class="play">
            <i class="fa-solid fa-play"></i>
        </div>
        <i class="fa-solid fa-forward-step"></i>
    </div>
</div>
</body>
</html>